export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const STAFFS_ADD = "STAFFS_ADD";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
export const DEPARTMENTS_ADD = "DEPARTMENTS_ADD";

export const SALARYS_LOADING = "SALARYS_LOADING";
export const SALARYS_FAILED = "SALARYS_FAILED";
export const SALARYS_ADD = "SALARYS_ADD";